apiVersion: v1
kind: Service
metadata:
  name: my-web
  namespace: myapp
  labels:
    run: my-web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-web
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: my-api
  namespace: myapp
  labels:
    run: my-api
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: my-web
  type: ClusterIP
