steps:

- name: gcr.io/k8s-skaffold/skaffold
  args:
    - skaffold
    - build
    - '--interactive=false'
    - '--file-output=artifacts.json'
    - --default-repo=us-central1-docker.pkg.dev/$PROJECT_ID/myrepo

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - '-c'
    - >
      gcloud beta deploy releases create rel-$(date +%H%M%S-%Y%m%d)
      --delivery-pipeline=shingo-app-test2 --build-artifacts=artifacts.json
      --region=us-central1
      --annotations=commitId=$REVISION_ID