apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-testrepo
build:
  artifacts:
  - image: my-nginx
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/*.yaml
# profiles:
#  - name: prod
#    deploy:
#      kubectl:
#        manifests:
#          - manifests/prod/*.yaml