apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: skaffold-testrepo
build:
  artifacts:
  - image: my-nginx
    docker:
      dockerfile: Dockerfile
  local:
    push: us-central1-docker.pkg.dev/shingo-new-proto/myrepo
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
