apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-testrepo
build:
  artifacts:
  - image: my-nginx
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    path: manifests/overlays/dev
profiles:
 - name: staging
   deploy:
     kustomize:
      path: manifests/overlays/staging
 - name: prod
   deploy:
     kustomize:
      path: manifests/overlays/prod