apiVersion: skaffold/v1
kind: Config
metadata:
  name: skaffold-testrepo
build:
  artifacts:
  - image: my-web
    docker:
      dockerfile: my-web/Dockerfile
    context: my-web
  - image: my-api
    docker:
      dockerfile: my-api/Dockerfile
    context: my-api
  local:
    useDockerCLI: true
deploy:
  kustomize:
    path: manifests/overlays/dev
profiles:
 - name: staging
   deploy:
     kustomize:
      path: manifests/overlays/staging
 - name: prod
   deploy:
     kustomize:
      path: manifests/overlays/prod