apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  selector:
    matchLabels:
      run: my-web
  replicas: 2
  template:
    metadata:
      labels:
        run: my-web
    spec:
      containers:
      - name: my-web
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
spec:
  selector:
    matchLabels:
      run: my-api
  replicas: 2
  template:
    metadata:
      labels:
        run: my-api
    spec:
      containers:
      - name: my-api
        image: nginx
        ports:
        - containerPort: 80
